title: HSMA Content Upload
description: > # this means to ignore newlines until "baseurl:"
  Content Upload Site für die HSMA.
permalink: ':title/'
baseurl: "/SID_SS19" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: HSMA # add your name
author-img: hsma.png # add your photo
about-author: Hochschule Mannheim. # add description
social-twitter: hsmanews # add your Twitter handle
social-facebook: HochschuleMannheim # add your Facebook handle
social-github: informatik-mannheim # add your Github handle
social-linkedin: /school/hochschule-mannheim # add your Linkedin handle
social-email: s.paulus@hs-mannheim.de # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
